version: '3'
services:
  backend:
    image: mui-backend
    container_name: mui-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./src:/app/src
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    container_name: postgres
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data-volume:
